package sbom

import (
	"archive/zip"
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/moby/buildkit/frontend/gateway/client"
	fstypes "github.com/tonistiigi/fsutil/types"

	"github.com/loganprice/mantle/internal/resolver"
)

func TestParseAPKDatabase(t *testing.T) {
	data := `P:busybox
V:1.36.1-r6
A:x86_64
T:Size optimized toolbox
L:GPL-2.0-only
U:https://busybox.net/

P:musl
V:1.2.4-r3
A:x86_64
T:the musl c library
L:MIT

P:python-3.12
V:3.12.8-r3
A:x86_64
T:A high-level scripting language
L:PSF-2.0

`

	pkgLookup := map[string]resolver.PackageInfo{
		"busybox=1.36.1-r6": {
			Name:    "busybox",
			Version: "1.36.1-r6",
			URL:     "https://packages.wolfi.dev/os/x86_64/busybox-1.36.1-r6.apk",
		},
	}

	components := parseAPKDatabase(data, pkgLookup)

	if len(components) != 3 {
		t.Fatalf("expected 3 components, got %d", len(components))
	}

	// Check busybox (should be enriched with URL from pkgLookup)
	checkBusybox(t, components[0])

	// Check musl (should NOT be enriched — not in pkgLookup)
	checkMusl(t, components[1])

	// Check python
	checkPython(t, components[2])
}

func checkBusybox(t *testing.T, bb Component) {
	t.Helper()
	if bb.Name != "busybox" {
		t.Errorf("name = %q, want %q", bb.Name, "busybox")
	}
	if bb.Version != "1.36.1-r6" {
		t.Errorf("version = %q, want %q", bb.Version, "1.36.1-r6")
	}
	if bb.PURL != "pkg:apk/wolfi/busybox@1.36.1-r6?arch=x86_64" {
		t.Errorf("purl = %q, want pkg:apk/wolfi/busybox@1.36.1-r6?arch=x86_64", bb.PURL)
	}
	if len(bb.ExternalRef) != 1 || bb.ExternalRef[0].URL != "https://packages.wolfi.dev/os/x86_64/busybox-1.36.1-r6.apk" {
		t.Errorf("expected enriched URL from pkgLookup, got %+v", bb.ExternalRef)
	}

	// Check verified property
	hasVerified := false
	for _, p := range bb.Properties {
		if p.Name == "mantle:verified" && p.Value == "true" {
			hasVerified = true
		}
	}
	if !hasVerified {
		t.Error("busybox should have mantle:verified=true property")
	}
}

func checkMusl(t *testing.T, musl Component) {
	t.Helper()
	if musl.Name != "musl" {
		t.Errorf("name = %q, want %q", musl.Name, "musl")
	}
	if len(musl.ExternalRef) != 0 {
		t.Errorf("musl should have no external ref from pkgLookup, got %+v", musl.ExternalRef)
	}
}

func checkPython(t *testing.T, py Component) {
	t.Helper()
	if py.Name != "python-3.12" {
		t.Errorf("name = %q, want %q", py.Name, "python-3.12")
	}
	if len(py.Licenses) != 1 || py.Licenses[0].License.Name != "PSF-2.0" {
		t.Errorf("expected PSF-2.0 license, got %+v", py.Licenses)
	}
}

func TestParsePythonMetadata(t *testing.T) {
	data := `Metadata-Version: 2.1
Name: requests
Version: 2.31.0
Summary: Python HTTP for Humans.
License: Apache-2.0
Author: Kenneth Reitz

A longer description follows...
`

	comp := parsePythonMetadata(data)

	if comp.Name != "requests" {
		t.Errorf("name = %q, want %q", comp.Name, "requests")
	}
	if comp.Version != "2.31.0" {
		t.Errorf("version = %q, want %q", comp.Version, "2.31.0")
	}
	if comp.PURL != "pkg:pypi/requests@2.31.0" {
		t.Errorf("purl = %q, want %q", comp.PURL, "pkg:pypi/requests@2.31.0")
	}
	if comp.Description != "Python HTTP for Humans." {
		t.Errorf("description = %q, want %q", comp.Description, "Python HTTP for Humans.")
	}

	hasEcosystem := false
	for _, p := range comp.Properties {
		if p.Name == "mantle:ecosystem" && p.Value == "python" {
			hasEcosystem = true
		}
	}
	if !hasEcosystem {
		t.Error("expected mantle:ecosystem=python property")
	}
}

func TestParsePythonMetadataCaseInsensitivePURL(t *testing.T) {
	data := `Name: Flask
Version: 3.0.0
Summary: A simple framework
`

	comp := parsePythonMetadata(data)
	if comp.PURL != "pkg:pypi/flask@3.0.0" {
		t.Errorf("purl = %q, want lowercase pkg:pypi/flask@3.0.0", comp.PURL)
	}
}

func TestParseAPKDatabaseEmpty(t *testing.T) {
	components := parseAPKDatabase("", nil)
	if len(components) != 0 {
		t.Errorf("expected 0 components for empty input, got %d", len(components))
	}
}

func TestParsePomProperties(t *testing.T) {
	data := `# Generated by Maven
groupId=org.apache.commons
artifactId=commons-lang3
version=3.14.0
`

	comp := parsePomProperties(strings.NewReader(data))

	if comp.Name != "org.apache.commons:commons-lang3" {
		t.Errorf("name = %q, want %q", comp.Name, "org.apache.commons:commons-lang3")
	}
	if comp.Version != "3.14.0" {
		t.Errorf("version = %q, want %q", comp.Version, "3.14.0")
	}
	if comp.PURL != "pkg:maven/org.apache.commons/commons-lang3@3.14.0" {
		t.Errorf("purl = %q, want %q", comp.PURL, "pkg:maven/org.apache.commons/commons-lang3@3.14.0")
	}

	hasEcosystem := false
	for _, p := range comp.Properties {
		if p.Name == "mantle:ecosystem" && p.Value == "java" {
			hasEcosystem = true
		}
	}
	if !hasEcosystem {
		t.Error("expected mantle:ecosystem=java property")
	}
}

func TestParsePomPropertiesNoGroupID(t *testing.T) {
	data := `artifactId=my-tool
version=1.0.0
`

	comp := parsePomProperties(strings.NewReader(data))
	if comp.Name != "my-tool" {
		t.Errorf("name = %q, want %q", comp.Name, "my-tool")
	}
}

func TestParseDepsJSON(t *testing.T) {
	data := []byte(`{
  "libraries": {
    "Newtonsoft.Json/13.0.3": {
      "type": "package"
    },
    "Microsoft.Extensions.Logging/8.0.0": {
      "type": "package"
    },
    "MyApp/1.0.0": {
      "type": "project"
    }
  }
}`)

	components := parseDepsJSON(data)

	// Should have 2 (project refs are skipped)
	if len(components) != 2 {
		t.Fatalf("expected 2 components, got %d", len(components))
	}

	found := make(map[string]bool)
	for _, c := range components {
		found[c.Name] = true
		if c.Name == "Newtonsoft.Json" {
			if c.Version != "13.0.3" {
				t.Errorf("version = %q, want 13.0.3", c.Version)
			}
			if c.PURL != "pkg:nuget/Newtonsoft.Json@13.0.3" {
				t.Errorf("purl = %q, want pkg:nuget/Newtonsoft.Json@13.0.3", c.PURL)
			}
		}
	}

	if !found["Newtonsoft.Json"] || !found["Microsoft.Extensions.Logging"] {
		t.Errorf("missing expected packages, found: %v", found)
	}
	if found["MyApp"] {
		t.Error("project reference MyApp should have been skipped")
	}
}

func TestParseDepsJSONEmpty(t *testing.T) {
	components := parseDepsJSON([]byte(`{}`))
	if len(components) != 0 {
		t.Errorf("expected 0 components for empty deps, got %d", len(components))
	}
}

func TestParseNodePackageJSON(t *testing.T) {
	tests := []struct {
		desc        string
		data        string
		wantName    string
		wantLicense []string
	}{
		{
			desc:        "string license (modern)",
			data:        `{"name": "foo", "version": "1.0", "license": "MIT"}`,
			wantName:    "foo",
			wantLicense: []string{"MIT"},
		},
		{
			desc:        "object license (legacy)",
			data:        `{"name": "foo", "version": "1.0", "license": {"type": "ISC", "url": "..."}}`,
			wantName:    "foo",
			wantLicense: []string{"ISC"},
		},
		{
			desc:        "licenses array (legacy)",
			data:        `{"name": "foo", "version": "1.0", "licenses": [{"type": "MIT"}, {"type": "Apache-2.0"}]}`,
			wantName:    "foo",
			wantLicense: []string{"MIT", "Apache-2.0"},
		},
		{
			desc:        "both license and licenses",
			data:        `{"name": "foo", "version": "1.0", "license": "GPL-3.0", "licenses": [{"type": "MIT"}]}`,
			wantName:    "foo",
			wantLicense: []string{"GPL-3.0", "MIT"},
		},
		{
			desc:        "no license",
			data:        `{"name": "foo", "version": "1.0"}`,
			wantName:    "foo",
			wantLicense: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			comp, ok := parseNodePackageJSON([]byte(tt.data))
			if !ok {
				t.Fatal("expected parse to succeed")
			}
			if comp.Name != tt.wantName {
				t.Errorf("name = %q, want %q", comp.Name, tt.wantName)
			}
			if len(comp.Licenses) != len(tt.wantLicense) {
				t.Fatalf("got %d licenses, want %d", len(comp.Licenses), len(tt.wantLicense))
			}
			for i, l := range tt.wantLicense {
				if comp.Licenses[i].License.Name != l {
					t.Errorf("license[%d] = %q, want %q", i, comp.Licenses[i].License.Name, l)
				}
			}
		})
	}
}

// -- mockReference for testing filesystem scanners natively --

// mockReference implements client.Reference for testing without requiring a real BuildKit daemon.
type mockReference struct {
	client.Reference // anonymous embed to fulfill interface methods we don't use
	files            map[string][]byte
}

func newMockReference() *mockReference {
	return &mockReference{
		files: make(map[string][]byte),
	}
}

// addFile provisions a synthetic file into our virtual filesystem.
func (m *mockReference) addFile(path string, content []byte) {
	m.files[filepath.Clean(path)] = content
}

// ReadFile specifically overrides the interface for our parsers.
func (m *mockReference) ReadFile(ctx context.Context, req client.ReadRequest) ([]byte, error) {
	data, ok := m.files[filepath.Clean(req.Filename)]
	if !ok {
		return nil, fmt.Errorf("file not found: %s", req.Filename)
	}

	if req.Range != nil {
		if req.Range.Offset >= len(data) {
			return nil, nil // EOF
		}
		end := req.Range.Offset + req.Range.Length
		if end > len(data) {
			end = len(data)
		}
		return data[req.Range.Offset:end], nil
	}
	return data, nil
}

// ReadDir simulates finding subdirectories for package traversal manually
func (m *mockReference) ReadDir(ctx context.Context, req client.ReadDirRequest) ([]*fstypes.Stat, error) {
	// Our mock finds immediate children constructed implicitly from the flat file map paths
	targetDir := filepath.Clean(req.Path)
	if !strings.HasSuffix(targetDir, "/") {
		targetDir += "/"
	}

	seen := make(map[string]bool)
	var entries []*fstypes.Stat

	found := false
	for p := range m.files {
		if strings.HasPrefix(p, targetDir) {
			found = true
			rel := strings.TrimPrefix(p, targetDir)
			parts := strings.SplitN(rel, "/", 2)

			childName := parts[0]
			if childName == "" || seen[childName] {
				continue
			}
			seen[childName] = true

			isDir := len(parts) > 1
			mode := uint32(0644)
			if isDir {
				mode = uint32(0755 | os.ModeDir) // Dir bit mask
			}

			entries = append(entries, &fstypes.Stat{
				Path: childName,
				Mode: mode,
				Size: int64(len(m.files[p])),
			})
		}
	}

	if !found {
		return nil, fmt.Errorf("directory not found: %s", req.Path)
	}
	return entries, nil
}

func TestScanner_Python(t *testing.T) {
	mock := newMockReference()
	// Provision Python METADATA file
	pyData := `Metadata-Version: 2.1
Name: requests
Version: 2.31.0
Summary: Python HTTP for Humans.
License: Apache-2.0
`
	mock.addFile("/usr/lib/python3.12/site-packages/requests-2.31.0.dist-info/METADATA", []byte(pyData))

	scanner := &pythonScanner{}
	comps := scanner.Scan(context.Background(), mock)

	if len(comps) != 1 {
		t.Fatalf("expected 1 python component, got %d", len(comps))
	}
	if comps[0].Name != "requests" || comps[0].Version != "2.31.0" {
		t.Errorf("expected requests 2.31.0, got %s %s", comps[0].Name, comps[0].Version)
	}
}

func TestScanner_Node(t *testing.T) {
	mock := newMockReference()
	// Provision Node.js package.json files
	pkg1 := `{"name": "lodash", "version": "4.17.21", "license": "MIT"}`
	pkg2 := `{"name": "@types/node", "version": "20.0.0", "license": "MIT"}`

	mock.addFile("/app/node_modules/lodash/package.json", []byte(pkg1))
	mock.addFile("/app/node_modules/@types/node/package.json", []byte(pkg2))

	scanner := &nodeScanner{}
	comps := scanner.Scan(context.Background(), mock)

	if len(comps) != 2 {
		t.Fatalf("expected 2 node components, got %d", len(comps))
	}

	foundLodash, foundNode := false, false
	for _, c := range comps {
		if c.Name == "lodash" {
			foundLodash = true
		}
		if c.Name == "@types/node" {
			foundNode = true
		}
	}
	if !foundLodash || !foundNode {
		t.Errorf("missing expected node packages")
	}
}

func TestScanner_Java(t *testing.T) {
	mock := newMockReference()

	// Build a valid ZIP (JAR) file containing a pom.properties in-memory
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	f, _ := w.Create("META-INF/maven/com.example/my-app/pom.properties")
	_, _ = f.Write([]byte(`groupId=com.example
artifactId=my-app
version=1.0.0
`))
	_ = w.Close()

	mock.addFile("/app/app.jar", buf.Bytes())

	scanner := &javaScanner{}
	comps := scanner.Scan(context.Background(), mock)

	if len(comps) != 1 {
		t.Fatalf("expected 1 java component, got %d", len(comps))
	}
	if comps[0].Name != "com.example:my-app" || comps[0].Version != "1.0.0" {
		t.Errorf("expected com.example:my-app 1.0.0, got %s %s", comps[0].Name, comps[0].Version)
	}
}

func TestScanner_Go(t *testing.T) {
	mock := newMockReference()

	// Compile a tiny valid ELF Go binary dynamically so buildinfo.Read can parse a real Linux binary organically.
	tmpDir, err := os.MkdirTemp("", "mantle-go-test-")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	srcFile := filepath.Join(tmpDir, "main.go")
	_ = os.WriteFile(srcFile, []byte(`package main; import _ "fmt"; func main() {}`), 0644)

	binFile := filepath.Join(tmpDir, "app")
	cmd := exec.Command("go", "build", "-o", binFile, srcFile)
	cmd.Env = append(os.Environ(), "GOOS=linux", "GOARCH=amd64") // Force ELF compilation
	if err := cmd.Run(); err != nil {
		t.Fatalf("failed to compile dummy ELF go binary: %v", err)
	}

	data, err := os.ReadFile(binFile)
	if err != nil {
		t.Fatalf("failed to read compiled dummy: %v", err)
	}

	mock.addFile("/usr/local/bin/my-go-app", data)

	scanner := &goScanner{}
	comps := scanner.Scan(context.Background(), mock)

	// An empty inline main.go has no external modules in its buildinfo deps
	if len(comps) != 0 {
		t.Fatalf("expected 0 external components for empty dummy program, got %d", len(comps))
	}
}

func TestScanAPK(t *testing.T) {
	mock := newMockReference()
	// Provision APK database natively
	dbData := `P:curl
V:8.5.0-r0
A:x86_64
T:URL retrieval utility
L:curl
U:https://curl.se/
`
	mock.addFile("/lib/apk/db/installed", []byte(dbData))

	comps, err := scanAPK(context.Background(), mock, map[string]resolver.PackageInfo{})
	if err != nil {
		t.Fatalf("unexpected error scanning mock APK db: %v", err)
	}

	if len(comps) != 1 {
		t.Fatalf("expected 1 APK component, got %d", len(comps))
	}
	if comps[0].Name != "curl" || comps[0].Version != "8.5.0-r0" {
		t.Errorf("expected curl 8.5.0-r0, got %s %s", comps[0].Name, comps[0].Version)
	}
}

func TestScanner_Dotnet(t *testing.T) {
	mock := newMockReference()

	// Provision .deps.json file natively
	depsData := `{
  "libraries": {
    "Newtonsoft.Json/13.0.3": {
      "type": "package"
    }
  }
}`
	mock.addFile("/app/my-app.deps.json", []byte(depsData))

	scanner := &dotnetScanner{}
	comps := scanner.Scan(context.Background(), mock)

	if len(comps) != 1 {
		t.Fatalf("expected 1 dotnet component, got %d", len(comps))
	}
	if comps[0].Name != "Newtonsoft.Json" || comps[0].Version != "13.0.3" {
		t.Errorf("expected Newtonsoft.Json 13.0.3, got %s %s", comps[0].Name, comps[0].Version)
	}
}
